# """each new term in the fibonaccii sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 term will be"""
#
# """ By considering the terms in the fibonacci sequence whose values do not exceed four million,
#  find the sum of the even valued terms"""
# n=10
# f=1
# s=2
# i=1
# sum=2
# while i<=n:
#     next= f+s
#     if next % 2!=0:continue
#     sum= sum + next
#     f=s
#     s=next
#     i+=1
# print(sum)
#
# #star printing code
# a = int(input())
# k = 1
# for i in range(0,a):
#     for j in range(0,i+1):
#         print("*", end="")
#         k = k+1
#     print()